config/routes.rb
Rails.application.routes.draw do
  resources :directors ,only:[:index, :show]
  resources :genres, only:[:index, :show]
  resources :home , only:[:index]
  resources :about , only:[:index]
  root to: 'home#index'
  resources :movies, only:[:index, :show]
  resources :actors, only:[:index, :show]

  resources :search ,only:[:index] do
    collection do
      get 'results'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
    has_many :movie_actors
    has_many :movies , through: :movie_actors

    validates :name , presence: true, uniqueness: true
    paginates_per 15
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
    has_many :movies
    paginates_per 15
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :movie_genres
    has_many :movies , through: :movie_genres

    validates :name , presence: true, uniqueness: true
    paginates_per 10
end

app/models/image.rb
class Image < ApplicationRecord
    has_one :movie

    validates :name , presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :image
  has_many :movie_actors
  has_many :actors , through: :movie_actors
  has_many :movie_genres
  has_many :genres , through: :movie_genres
  belongs_to :director

  validates :title , presence: true
  validates :year ,  numericality: { only_integer: true }


  paginates_per 10

end

app/models/movie_actor.rb
class MovieActor < ApplicationRecord
  belongs_to :movie
  belongs_to :actor
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :movie
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all.page params[:page]
  end

  def show
    @actor = Actor.find(params[:id])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all.page params[:page]
  end

  def show
    @genre = Genre.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Movie Hub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/full-width-pics.css" rel="stylesheet">

  </head>

  <body>
    <header id="app">
      <h1>The Movie Hub</h1>
    </header>
    <nav id = "nav">
          <ul id="list">
            <li>
              <%= link_to "Home" , home_index_path%>
            </li>
            <li>
              <%= link_to "About" , about_index_path%>
            </li>
            <li>
              <%= link_to "Movies" , movies_path%>
            </li>
            <li>
              <%= link_to "Actors" , actors_path%>
            </li>
            <li>
              <%= link_to "Genres" , genres_path%>
            </li>
            <li>
              <%= link_to "Directors" , directors_path%>
            </li>
          </ul>
    </nav>
    <div id = "search">
          <%= form_tag(results_search_index_path, method: "get") do %>
            <%= label_tag(:q, "Search for:") %>
            <%= text_field_tag(:q) %>
            <%= collection_select(:query_genre , :genre_id , Genre.all.order(:name), :id ,:name,{:include_blank => 'Movie Title'})%>
            <%= submit_tag("Search") %>
          <% end %>
    </div>
    
    <%= yield %>
     <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">The Movie Hub 2018</p>
      </div>
    </footer>
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  </body>
</html>